// src/lib/notificationTypes.ts

export type NotificationCategory =
  | "attendance"
  | "leave"
  | "task"
  | "meeting"
  | "message"
  | "emergency"
  | "ai"
  | "productivity"
  | "system";

export type NotificationPriority = "low" | "medium" | "high" | "emergency";

export interface NotificationActionButton {
  action: string;
  title: string;
  icon?: string;
}

export interface EnterpriseNotification {
  id: string;
  userId: string;
  companyId?: string;
  category: NotificationCategory;
  event: string;
  title: string;
  body: string;
  icon?: string; // emoji or URL
  imageUrl?: string;
  priority: NotificationPriority;
  isRead: boolean;
  clickAction?: string; // URL to open on click
  actionButtons?: NotificationActionButton[];
  data?: Record<string, string>;
  createdAt: any; // Firestore Timestamp
  expiresAt?: any;
}

// Notification events list (60+ events covering all modules)
export const NOTIFICATION_EVENTS = {
  attendance: {
    CHECK_IN_REMINDER: "ATTENDANCE_CHECK_IN_REMINDER",
    CHECK_OUT_REMINDER: "ATTENDANCE_CHECK_OUT_REMINDER",
    BREAK_EXCEEDED: "ATTENDANCE_BREAK_EXCEEDED",
    CHECKIN_SUCCESS: "ATTENDANCE_CHECKIN_SUCCESS",
    CHECKOUT_SUCCESS: "ATTENDANCE_CHECKOUT_SUCCESS",
    LATE_WARNING: "ATTENDANCE_LATE_WARNING",
    MISSED_ATTENDANCE: "ATTENDANCE_MISSED",
    OVERTIME_DETECTED: "ATTENDANCE_OVERTIME_DETECTED",
    CORRECTION_SUBMITTED: "ATTENDANCE_CORRECTION_SUBMITTED",
    CORRECTION_APPROVED: "ATTENDANCE_CORRECTION_APPROVED",
    CORRECTION_REJECTED: "ATTENDANCE_CORRECTION_REJECTED",
    EMPLOYEE_ABSENT: "ATTENDANCE_EMPLOYEE_ABSENT", // Admin/Manager alert
    SUSPICIOUS_LOGIN: "ATTENDANCE_SUSPICIOUS_LOGIN", // Admin alert
  },
  leave: {
    LEAVE_SUBMITTED: "LEAVE_SUBMITTED",
    LEAVE_APPROVED: "LEAVE_APPROVED",
    LEAVE_REJECTED: "LEAVE_REJECTED",
    LEAVE_CANCELLED: "LEAVE_CANCELLED",
    LEAVE_BALANCE_LOW: "LEAVE_BALANCE_LOW",
    LEAVE_STARTS_TOMORROW: "LEAVE_STARTS_TOMORROW",
    RETURN_REMINDER: "LEAVE_RETURN_REMINDER",
    NEW_LEAVE_REQUEST: "LEAVE_NEW_REQUEST", // Manager alert
    TEAM_SHORTAGE: "LEAVE_TEAM_SHORTAGE", // Manager alert
  },
  task: {
    TASK_ASSIGNED: "TASK_ASSIGNED",
    TASK_UPDATED: "TASK_UPDATED",
    PRIORITY_CHANGED: "TASK_PRIORITY_CHANGED",
    DEADLINE_APPROACHING: "TASK_DEADLINE_APPROACHING",
    DEADLINE_MISSED: "TASK_DEADLINE_MISSED",
    TASK_COMMENTED: "TASK_COMMENTED",
    TASK_APPROVED: "TASK_APPROVED",
    TASK_REJECTED: "TASK_REJECTED",
    MENTIONED_IN_COMMENT: "TASK_MENTIONED_IN_COMMENT",
    SUBTASK_ASSIGNED: "TASK_SUBTASK_ASSIGNED",
    STATUS_CHANGED: "TASK_STATUS_CHANGED",
    TASK_DONE: "TASK_DONE",
    TASK_OVERDUE: "TASK_OVERDUE", // Manager alert
    SPRINT_DELAYED: "TASK_SPRINT_DELAYED", // Manager alert
  },
  meeting: {
    MEETING_SCHEDULED: "MEETING_SCHEDULED",
    MEETING_REMINDER_15: "MEETING_REMINDER_15",
    MEETING_CANCELLED: "MEETING_CANCELLED",
    MEETING_RESCHEDULED: "MEETING_RESCHEDULED",
    ADDED_TO_MEETING: "MEETING_ADDED_TO_MEETING",
    RECORDING_AVAILABLE: "MEETING_RECORDING_AVAILABLE",
    AI_SUMMARY_READY: "MEETING_AI_SUMMARY_READY",
    MEETING_CONFLICT: "MEETING_CONFLICT", // Manager alert
  },
  message: {
    DM_RECEIVED: "MESSAGE_DM_RECEIVED",
    TEAM_MESSAGE: "MESSAGE_TEAM_RECEIVED",
    MENTION: "MESSAGE_MENTION",
    REPLY: "MESSAGE_REPLY",
    ANNOUNCEMENT: "MESSAGE_ANNOUNCEMENT",
  },
  emergency: {
    OFFICE_CLOSED: "EMERGENCY_OFFICE_CLOSED",
    OUTAGE_ALERT: "EMERGENCY_OUTAGE_ALERT",
    SECURITY_EMERGENCY: "EMERGENCY_SECURITY_ALERT",
    EMERGENCY_MEETING: "EMERGENCY_MEETING",
    WEATHER_WARNING: "EMERGENCY_WEATHER_WARNING",
    FIRE_DRILL: "EMERGENCY_FIRE_DRILL",
  },
  ai: {
    BREAK_REMINDER: "AI_BREAK_REMINDER",
    BURNOUT_RISK: "AI_BURNOUT_RISK",
    FOCUS_MODE: "AI_FOCUS_MODE",
    DAILY_UPDATE_PENDING: "AI_DAILY_UPDATE_PENDING",
    HOURS_BELOW_TARGET: "AI_HOURS_BELOW_TARGET",
    PRODUCTIVITY_WARNING: "AI_PRODUCTIVITY_WARNING",
    DEADLINE_RISK: "AI_DEADLINE_RISK",
  },
  productivity: {
    WEEKLY_HOURS_DONE: "PRODUCTIVITY_WEEKLY_HOURS",
    MILESTONE_REACHED: "PRODUCTIVITY_MILESTONE",
    FOCUS_STREAK: "PRODUCTIVITY_STREAK",
    WORK_ANNIVERSARY: "PRODUCTIVITY_ANNIVERSARY",
    BADGE_EARNED: "PRODUCTIVITY_BADGE",
    LEADERBOARD_UPDATE: "PRODUCTIVITY_LEADERBOARD",
  },
  system: {
    PASSWORD_CHANGED: "SYSTEM_PASSWORD_CHANGED",
    MFA_ENABLED: "SYSTEM_MFA_ENABLED",
    NEW_DEVICE_LOGIN: "SYSTEM_NEW_DEVICE",
    MAINTENANCE_SCHEDULED: "SYSTEM_MAINTENANCE",
  },
} as const;
